spring:
  application:
    name: inventory-service
  datasource:
    name: inventory_service
    url: jdbc:postgresql://postgres:5432/inventory_service
    username: myuser
    password: secret
  threads:
    virtual:
      enabled: true
server:
  port: 0
application:
  jwt:
    secret: verysecretkeyWhichIsVeryLongAndHardToGuessSoYouShouldChangeItPleaseAndThankYou
    header: Authorization
    prefix: Bearer
    expiration: 86400000
api:
  key:
    self: INVENTORY_SERVICE_TOKEN
eureka:
  client:
    service-url:
      defaultZone: http://eureka:passw0rd@discovery-server:8761/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
loki:
  url: http://loki:3100/loki/api/v1/push
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  observations:
    key-values:
      application: api-gateway
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411